services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: desafio-dev-api-rest-app
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
